server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://vr-va-beneficios.com.br
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniautorizador?useTimezone=true&serverTimezone=UTC
    username: root
    password: adm123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    show-sql: false
